# Generated by Django 3.0 on 2019-12-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesModel',
            fields=[
                ('geographymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='geography.GeographyModel')),
                ('places_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('contact', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cartegory', models.CharField(choices=[('RESIDENTIALS', 'residentials'), ('EDUCATION', 'education'), ('HEALTH', 'health'), ('HOSPITALITY', 'hospitality'), ('SPORTS', 'sports'), ('ART', 'art'), ('FARM', 'farm'), ('OFFICES', 'offices'), ('SHOPS', 'shops'), ('SERVICES', 'services')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('geography.geographymodel',),
        ),
        migrations.CreateModel(
            name='WebPagesModel',
            fields=[
                ('webpages_id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=100, unique=True)),
                ('subtittle', models.CharField(max_length=120, null=True)),
                ('about_us', models.CharField(max_length=300, null=True)),
                ('footer', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webpage', to='places.PlacesModel')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('services_id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100, unique=True)),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='places.WebPagesModel')),
            ],
        ),
        migrations.CreateModel(
            name='CarusselModel',
            fields=[
                ('carussel_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='carussel')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carussel', to='places.WebPagesModel')),
            ],
        ),
    ]
